"""
Script to take the full contents of data.lsdb.io/data/catalogs.json file
and convert entries into registry resources.

Install its dependencies with `pip install -e '.[dev]'` from the root of the repository.
"""

import argparse
import json
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from urllib.parse import urlparse
from xml.etree import ElementTree

import hats
import tabulate
from hats.catalog.catalog_collection import CatalogCollection
from jinja2 import Environment, FileSystemLoader
from tqdm import tqdm

ROOT_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = ROOT_DIR / "templates"
TIMESTAMP = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")

# Resources that are maintained by hand, not generated by this script.
STATIC_RESOURCES = {"registry", "authority"}

# Hosts of the catalogs we register, mapped to their (location, short location).
LOCATIONS = {"data.lsdb.io": ("UW/Epyc", "uw")}

# Format of the catalog ids set in data.lsdb.io.
ID_PATTERN = re.compile(r"[a-z0-9_]+")


class ResourceError(Exception):
    """Raised when catalog ids are invalid, or resources would share an identifier."""


@dataclass
class Catalog:
    """A catalog from data.lsdb.io to be registered."""

    label: str  # Its directory in data.lsdb.io, e.g. "ZTF/ZTF_DR14_(objects)".
    info: dict  # The contents of its catalog.json.
    url: str
    location: str
    short_location: str

    @property
    def id(self):
        """The catalog's id in data.lsdb.io, which names its resource file."""
        return self.info.get("id")

    @property
    def identifier(self):
        """The IVOA identifier of the catalog's resource."""
        return f"ivo://data.lsdb/{self.short_location}/{self.id}"


def _dir_name(label):
    return label.replace(" ", "_").replace("≥", "gte")


def _iter_catalog_dirs(entries, parent=""):
    """Yield the data.lsdb.io directory of every leaf catalog in catalogs.json."""
    for entry in entries:
        if isinstance(entry, str):
            yield f"{parent}/{_dir_name(entry)}" if parent else _dir_name(entry)
        elif "catalogs" in entry:
            group = f"{parent}/{_dir_name(entry['label'])}" if parent else _dir_name(entry["label"])
            yield from _iter_catalog_dirs(entry["catalogs"], group)


def _resolve_catalog_url(info):
    """Return (url, skip_reason) for a catalog.

    skip_reason is a non-None string when the catalog should be skipped.
    url is None whenever skip_reason is set.
    """
    if info.get("skip_connectivity_check"):
        return None, info["skip_connectivity_check"]

    urls = info.get("urls", {})
    url = urls.get("collection") or urls.get("catalog")

    if not url:
        return None, "no catalog URL"
    if url.endswith(".parquet"):
        return None, "single parquet file"
    if urlparse(url).hostname not in LOCATIONS:
        return None, "not a LINCC Frameworks-controlled catalog"

    return url, None


def _collect_catalogs(data_dir, report):
    """Return the catalogs to register, adding the ones that are skipped to the report."""
    with open(data_dir / "catalogs.json", encoding="utf-8") as f:
        catalog_dirs = list(_iter_catalog_dirs(json.load(f)))

    catalogs = []
    for label in catalog_dirs:
        catalog_json_path = data_dir / label / "catalog.json"
        if not catalog_json_path.exists():
            report.append([label, "", "catalog.json not found"])
            continue

        with open(catalog_json_path, encoding="utf-8") as f:
            info = json.load(f)

        url, skip_reason = _resolve_catalog_url(info)
        if skip_reason:
            report.append([label, "", skip_reason])
            continue

        catalogs.append(Catalog(label, info, url, *LOCATIONS[urlparse(url).hostname]))
    return catalogs


def _read_resources(resource_dir):
    """Map the name of each generated resource in resource_dir, active or deleted, to its metadata."""
    resources = {}
    for path in resource_dir.glob("*.xml"):
        if path.stem in STATIC_RESOURCES:
            continue
        try:
            root = ElementTree.parse(path).getroot()
            resources[path.stem] = {
                "name": path.stem,
                "status": root.get("status"),
                "created": root.get("created"),
                "title": root.find("title").text,
                "shortName": root.find("shortName").text,
                "identifier": root.find("identifier").text,
            }
        except Exception:
            print("error reading file", path)
            raise
    return resources


def _find_id_problems(catalogs):
    """List the catalogs with a missing or malformed id, and the ids shared by several catalogs."""
    problems = [
        f"{catalog.label} has an invalid id: {catalog.id!r}"
        for catalog in catalogs
        if not isinstance(catalog.id, str) or not ID_PATTERN.fullmatch(catalog.id)
    ]
    labels_by_id = defaultdict(list)
    for catalog in catalogs:
        labels_by_id[catalog.id].append(catalog.label)
    problems += [
        f"{catalog_id} is the id of {', '.join(labels)}"
        for catalog_id, labels in labels_by_id.items()
        if len(labels) > 1
    ]
    return problems


def _record_name(resource):
    """Name the deleted record of a resource's identifier after its last segment."""
    return resource["identifier"].rsplit("/", 1)[-1]


def _find_identifier_conflicts(resources, planned):
    """
    List the identifiers that several resources (active or deleted) would share once the planned
    resources are written.

    `resources` maps the name of every resource on disk to its metadata, and `planned` maps the
    name of every resource about to be written to its identifier.
    """
    identifiers = {name: resource["identifier"] for name, resource in resources.items()} | planned
    files_by_identifier = defaultdict(list)
    for name, identifier in sorted(identifiers.items()):
        files_by_identifier[identifier].append(f"{name}.xml")
    return [
        f"{identifier} would be the identifier of {', '.join(files)}"
        for identifier, files in files_by_identifier.items()
        if len(files) > 1
    ]


def _render_resource(template, catalog, existing, short_name_max):
    """Render the XML resource for a catalog, reading its properties with hats."""
    hats_catalog = hats.read_hats(catalog.url)
    if isinstance(hats_catalog, CatalogCollection):
        hats_catalog = hats_catalog.main_catalog
    properties = hats_catalog.catalog_info.extra_dict()

    created = existing["created"] if existing is not None else properties.get("hats_creation_date", TIMESTAMP)

    other_urls = catalog.info.get("other_urls", [])
    return template.render(
        name=catalog.info.get("name", ""),
        description=catalog.info.get("description", ""),
        accessUrl=catalog.url,
        referenceUrl=other_urls[0]["url"] if other_urls else "",
        shortName=catalog.id[:short_name_max],
        identifier=catalog.identifier,
        location=catalog.location,
        wavebands=properties.get("obs_regime", "Optical").split(" "),
        created=created,
        updated=TIMESTAMP,
        all_sky=float(properties.get("moc_sky_fraction", 0.0)) == 1.0,
    )


def run(data_dir, resource_dir, short_name_max=16, refresh_resources=False, rerender_list=()):
    """Write a resource for every new catalog, and mark resources of removed catalogs as deleted.

    If re-rendering a resource changes its identifier, a deleted record of the old identifier is kept.

    Raises a ResourceError, before writing any file, if catalog ids are missing, malformed or
    duplicated, or if resources would share an identifier or a file name.
    """
    jinja = Environment(loader=FileSystemLoader(TEMPLATES_DIR))
    template = jinja.get_template("vo-registry.xml.jinja")
    deleted_template = jinja.get_template("vo-registry-deleted.xml.jinja")

    resources = _read_resources(resource_dir)
    active_resources = {
        name: resource for name, resource in resources.items() if resource["status"] == "active"
    }
    report = []
    catalogs = _collect_catalogs(data_dir, report)
    if problems := _find_id_problems(catalogs):
        raise ResourceError("No resources were written, because of invalid ids:\n  " + "\n  ".join(problems))

    to_render = []
    for catalog in catalogs:
        if catalog.id in active_resources and not refresh_resources and catalog.label not in rerender_list:
            report.append([catalog.label, "", "skipped = existing"])
        else:
            to_render.append(catalog)

    # When an existing resource's identifier changes, the old identifier is kept as a deleted record,
    # in a file named after its last segment, so that harvesters know it's gone.
    retired = {
        catalog.id: active_resources[catalog.id]
        for catalog in to_render
        if catalog.id in active_resources and active_resources[catalog.id]["identifier"] != catalog.identifier
    }
    retired_names = {catalog_id: _record_name(resource) for catalog_id, resource in retired.items()}

    taken_names = resources.keys() | {catalog.id for catalog in catalogs}
    conflicts = [
        f"{name}.xml can't be the deleted record of {retired[catalog_id]['identifier']}: the name is taken"
        for catalog_id, name in retired_names.items()
        if name in taken_names
    ]
    planned = {catalog.id: catalog.identifier for catalog in to_render}
    planned |= {name: retired[catalog_id]["identifier"] for catalog_id, name in retired_names.items()}
    conflicts += _find_identifier_conflicts(resources, planned)
    if conflicts:
        raise ResourceError(
            "No resources were written, because of the following conflicts:\n  " + "\n  ".join(conflicts)
        )

    def write_deleted_record(name, resource):
        record = deleted_template.render(**resource, updated=TIMESTAMP)
        (resource_dir / f"{name}.xml").write_text(record, encoding="utf-8")
        report.append([name, "REMOVED", resource["identifier"]])

    for catalog in tqdm(to_render, desc="Rendering catalogs"):
        try:
            resource = _render_resource(template, catalog, active_resources.get(catalog.id), short_name_max)
            (resource_dir / f"{catalog.id}.xml").write_text(resource, encoding="utf-8")
            report.append([catalog.label, "SUCCESS", ""])
        except Exception as e:
            report.append([catalog.label, "", e])
            continue
        if catalog.id in retired:
            write_deleted_record(retired_names[catalog.id], retired[catalog.id])

    for name in sorted(active_resources.keys() - {catalog.id for catalog in catalogs}):
        write_deleted_record(name, active_resources[name])

    print(tabulate.tabulate(report, headers=["label", "success", "exception notes"]))

    # Quickly validate that everything is ok with the new XML files.
    _read_resources(resource_dir)


def main():
    """Parse the command-line arguments and generate the resources."""
    parser = argparse.ArgumentParser("vo-resource-gen")
    parser.add_argument(
        "--data_dir",
        help="The source of truth for list of catalogs.",
        type=Path,
        default=ROOT_DIR.parent / "data.lsdb.io" / "data",
    )
    parser.add_argument(
        "--out_dir",
        help="The directory to output records to.",
        type=Path,
        default=ROOT_DIR / "resources" / "data.lsdb.io",
    )
    parser.add_argument(
        "--short_name_max",
        help="Maximum allowable length of the VOResource short name.",
        type=int,
        default=16,
    )
    parser.add_argument(
        "--refresh_resources",
        help="Update the values of existing resources. Otherwise, skip those files.",
        action="store_true",
    )
    parser.add_argument(
        "--rerender_list",
        help="List of comma-separated labels to re-render the XML.",
        default="",
    )
    args = parser.parse_args()
    rerender_list = args.rerender_list.split(",") if args.rerender_list else []

    print("resource_dir  ", args.out_dir)
    print("data_dir      ", args.data_dir)
    print("rerender_list ", rerender_list)

    try:
        run(
            args.data_dir,
            args.out_dir,
            short_name_max=args.short_name_max,
            refresh_resources=args.refresh_resources,
            rerender_list=rerender_list,
        )
    except ResourceError as e:
        sys.exit(str(e))


if __name__ == "__main__":
    main()
