name: Deploy registry

on:
  push:
    branches: [main, deploy]

concurrency:
  group: "deployment"
  cancel-in-progress: false

env:
  DEPLOY_USER: registry
  DEPLOY_HOST: lsdb.phys.cmu.edu
  DOCKER_CONTEXT: registry-prod
  # The path to the clone of this repo on the server.
  REGISTY_LSDB_IO: /opt/services/vo_registry/registry.lsdb.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup SSH
        run: |
          mkdir -p ${HOME}/.ssh
          echo "${{ secrets.LSDB_PHYS_CMU_EDU_SSH_KEY }}" > ${HOME}/.ssh/id_rsa
          ls -lk ${HOME}/.ssh/id_rsa
          chmod 600 ${HOME}/.ssh/id_rsa
          ssh-keyscan -t ssh-rsa $DEPLOY_HOST >> ${HOME}/.ssh/known_hosts

      # Pull the repo's XML resources on the server.
      # The authority.xml and registry.xml files are copied over from
      # the resources dir of the private repo.
      - name: Sync resources in the server
        run: |
          ssh -i "${HOME}/.ssh/id_rsa" "${DEPLOY_USER}@${DEPLOY_HOST}" '
            set -e
            cd ${REGISTY_LSDB_IO}
            git fetch --prune origin
            git reset --hard origin/main
            RESOURCES_DIR="${REGISTY_LSDB_IO}/resources"
            FLAT_RESOURCES_DIR="${REGISTY_LSDB_IO}/_resources"
            scripts/flatten_resources.sh ${RESOURCES_DIR} ${FLAT_RESOURCES_DIR}
            cp $RESOURCES_DIR/authority.xml $FLAT_RESOURCES_DIR/authority.xml
            cp $RESOURCES_DIR/registry.xml $FLAT_RESOURCES_DIR/registry.xml
          '

      # Restart the container so it re-reads the (bind-mounted) flat dir.
      - name: Restart the registry service
        run: |
          docker context create $DOCKER_CONTEXT --docker "host=ssh://${DEPLOY_USER}@${DEPLOY_HOST}"
          docker context use $DOCKER_CONTEXT
          docker restart vo_registry
